plugins {
  id "org.springframework.boot" version "3.2.5" apply false
  id "io.spring.dependency-management" version "1.1.4" apply false
  id "com.diffplug.spotless" version "6.25.0" apply false
}

allprojects {
  group = "com.marioalba" // we can rename later if you want
  version = "0.0.1-SNAPSHOT"

  repositories {
    mavenCentral()
  }
}

subprojects {
  apply plugin: "java"
  apply plugin: "io.spring.dependency-management"
  apply plugin: "com.diffplug.spotless"

  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(21)
    }
  }

  tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
  }

  dependencies {
    // Lombok (compile time only)
    compileOnly "org.projectlombok:lombok:1.18.32"
    annotationProcessor "org.projectlombok:lombok:1.18.32"

    testCompileOnly "org.projectlombok:lombok:1.18.32"
    testAnnotationProcessor "org.projectlombok:lombok:1.18.32"

    testImplementation platform("org.junit:junit-bom:5.10.2")
    testImplementation "org.junit.jupiter:junit-jupiter"
  }

  spotless {
    java {
      // Format Java sources
      googleJavaFormat("1.19.2")
      target("src/**/*.java")
      removeUnusedImports()
      trimTrailingWhitespace()
      endWithNewline()
    }
    format("misc") {
      target("**/*.md", "**/.gitignore", "**/*.yml", "**/*.yaml")
      trimTrailingWhitespace()
      endWithNewline()
    }
  }


  test {
    useJUnitPlatform()
  }
}