plugins {
    id "org.springframework.boot"
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-validation"

    implementation platform("software.amazon.awssdk:bom:2.25.60")
    implementation "software.amazon.awssdk:dynamodb"
    implementation "software.amazon.awssdk:sqs"
    implementation "software.amazon.awssdk:sns"

    implementation project(":libs:common-events")
}
