server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingdb
    username: barber
    password: barber
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  flyway:
    enabled: true

aws:
  region: us-east-1
  endpoint: http://localhost:4566

booking:
  saga:
    pending-timeout-seconds: 30
    timeout-scan-ms: 1000

messaging:
  sns:
    bookingsTopicArn: arn:aws:sns:us-east-1:000000000000:bookings
  sqs:
    resultsQueueUrl: http://localhost:4566/000000000000/booking-availability-results
